### ISSUE TITLE
Custom Signs Exercise Needs Grammatical Improvement

### ISSUE THREAD

**Issue by atj-craig** [exercism/javascript#1524]
Hello!

I just discovered that the [Custom Signs](https://exercism.org/tracks/javascript/exercises/custom-signs/) exercise expects the following to be returned for the buildBirthdaySign function:
> Expected: "Happy Birthday! What **a old** fellow you are."

Grammatically, it would be correct to return this instead:
> Received: "Happy Birthday! What **an old** fellow you are."

I can see the solution to this in the _custom-signs.spec.js_ file. I'll submit a fix for this in the code.

However, it may be good to also update the instructions on the exercise to prompt the learner to be mindful of the grammatical difference and code appropriately.

**Comment by SleeplessByte** [comment]
We'll happily take your PR for the test fix. I don't know if the lesson in grammar is prompted in this exercise.

**Comment by atj-craig** [comment]
Fair enough :)

I've got the PR ready on my comp, but I don't have access to push. Would you be able to grant me basic access?

**Comment by junedev** [comment]
@atj-craig The workflow to propose changes is to fork the repository, then do your change in the fork and create a PR from there against the original repository (GitHub will prompt you for this automatically). That way no access rights are needed, everyone can contribute.

Instead of fixing this grammar mistake and with that increasing the length of the ternary operator statement, can you maybe think of a synonym for "old" that we could use instead to avoid the problem altogether? As @SleeplessByte pointed out, the grammar is not the point of the exercise and I would like to keep the exercise friendly for non-native speakers that might not be that versed in English grammar.

**Comment by atj-craig** [comment]
Sure, I'll do that. Thank you for the advice.
