### ISSUE TITLE
Translation Service: Missing test case

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1649]
From @kroitor in #1644:

> I think, the tests for this exercise are lacking an edge case, where the user should not call api.request if the resource is known to be Untranslatable from api.fetch right away. If we add that edge case to the test, the existing exemplar will fail, cause it sends an api.request on all failures even when it already knows that the resource is Untranslatable. Which is why I think the exemplar is wrong, despite that it satisfies the tests.

The alternative to fixing the tests and exemplar solution would be to change the instructions. My current feeling is there is value in following the current instructions though.

**Comment by SleeplessByte** [comment]
There is no such edge case. It's perfectly fine to call `request` if `fetch` returns `Untranslatable`, given the constraints of the instructions / the constraints of the API. Therefore, adding that test case, changes the instructions, and also changes the exemplar.  However, the exercise was written like this to allow for those error types to exists without requiring to import them, at all.

Happy to improve the exercise though. We merged it because we wanted to have it out there so we could collect commentary like this, so I see that as a win. In this particular case, I'd like to make the exercise clearer, but the nature of _forcing_ a-synchronicity, and having to force someone to use `.catch` (or async/await with try/catch) can, I think, not be captured in a simpler exercise.

It does sound like Igor did enjoy the exercise, so happy to continue the work on this exercise.

**Comment by kroitor** [comment]
@SleeplessByte 

> It's perfectly fine to call request if fetch returns Untranslatable, given the constraints of the instructions / the constraints of the API.

The instructions on this specific task are:

> - If `api.fetch` resolves, check the quality before resolving
> - If `api.fetch` rejects with `NotAvailable`, _request_ the translation instead
> - If `api.fetch` rejects with `Untranslatable`, forward the error
> - If _requesting_ rejects, forward the error

From there I assumed that a call to `request()` should be done only in the `NotAvailable` case. Which is why this exercise was a bit confusing for me. I mean, the exercise itself is good, just the instructions could be enhanced. Thanks for your replies!

**Comment by SleeplessByte** [comment]
Oh yeah. I can absolutely understand how you'd think that or see that. I was just commenting on the viewpoint of the constraints when I wrote this exercise at 4 in the morning before we knew what V3 would look like 😂.

We could do various things among hiding the errors in the test file.

We could also (not exclusively) amend the instructions to make it clear that:
- you can call request even if fetch fails (easiest solution)
- you should not call request when fetch fails with untranslatable + show you how you could check that. For example, if we hide the errors, you cannot use instanceof, but we could use the prototype name, or a magic property we add.

**Comment by kroitor** [comment]
@SleeplessByte i think those instructions could be amended like this (this would be the least intrusive change):

> - If `api.fetch` resolves, check the quality before resolving
> - If `api.fetch` rejects, _request_ the translation instead
> - If _requesting_ rejects, forward the error

**Comment by SleeplessByte** [comment]
I like that.

@junedev what do you think about this?

**Comment by junedev** [comment]
Changing the instructions is fine for me as well. I like the suggestion.

**Comment by SleeplessByte** [comment]
@kroitor would you like to submit a PR?

**Comment by kroitor** [comment]
@SleeplessByte yep, will do shortly!
