### ISSUE TITLE
Need to enhance the question to more understandable for students.

### ISSUE THREAD

**Issue by NoteLyfe** [exercism/javascript#1779]
3. Calculate the discounted rate for large projects question is not much understandable what to find and what not. Please explain it more clearly with each step what we have to find in it.

**Comment by junedev** [comment]
@NoteLyfe Sorry you had to wait for a reply this long.

Since we did not get other reports about problems with this task, I would like to ask you the following questions to narrow down the issue.
* When you were struggling with task 3, did you try to use the hints to solve it? Did you still have issues after making use of the hints?
* Do you have a concrete idea what should be changed/added in the description to improve it?

Please keep in mind that Exercism is not meant as platform for people that are new to programming. It is meant for people that already know at least one language reasonably well and want to learn another one. It case you are rather new to programming in general, maybe some of these general resources on problem solving are helpful to you: https://exercism.org/docs/tracks/python/problem-solving (The link leads to the Python track but the content is not Python specific.)

**Comment by junedev** [comment]
I'm closing this as it seems abandoned.
