### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by MikeHud** [exercism/javascript#1886]
The instructions recommend to use console.log for debugging but the browser does not output such messages. 

This is a big one because console.log is so valuable for debugging, but also the general learning experience

**Comment by SleeplessByte** [comment]
Hi there @MikeHud.

The `console.log` statements do not log to the browser because the `console` called from the code isn't the _browser console_. It's the console on whichever environment the tests run on. For example, if you were to run `console.log` when running this on a computer via node, it will, by default, log to the terminal (Terminal, bash, cmd.exe, powershell, etc.). 

Exercism's JavaScript track exercises have their tests ran by the javascript-test-runner which attempt to redirect `console.log` calls back to the test output.

![Exercism JavaScript exercise code editor with console.log statement in the code panel and test output on the side panel. The test output shows the test code ran, the test error, and the log output](https://user-images.githubusercontent.com/1964376/187470562-37a4f0ae-c791-4e9f-902c-face72a5d57d.png)

**Comment by MikeHud** [comment]
Oh, how strange. Suddenly the 'Your Output' in the Results section appears. I just got onto the 'Lasagna Master' exercise and now I can console.log!! maybe that's some weird coincidence though but I'm sure it wasn't working previously. And yes I understand it won't log to the browser, since it's running inside the test protocols. 

Anyway, great and thank you :-)

**Comment by SleeplessByte** [comment]
Sweet. Thanks for confirming it works now.

If you run into this issue again, could you post here / open a new issue including your exercism username and the Exercise? We'll then be able to investigate.
