### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/javascript#313]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by rchavarria** [comment]
Mandatory files are present, and they explain what they're supposed to explain. But links to images should be fixed:

- [ ] On `TESTS.md`, link to *Solution explorer* should be fixed as it is recommended on exercism.io documentation, with a relative path instead of `http://x.exercism.io/v3/tracks/javascript/docs/img/SolutionExplorer.png`
- [ ] On `TESTS.md`, link to *Add files* should be fixed as it is recommended on exercism.io documentation, with a relative path instead of `http://x.exercism.io/v3/tracks/javascript/docs/img/AddFiles.png`

@exercism/javascript, any other suggestion?

**Comment by matthewmorgan** [comment]
@rchavarria I haven't had a chance to read this yet, but I will get to it by the weekend.  I will also check it out for ES.  Thanks!

**Comment by rchavarria** [comment]
I label this as "good first patch". The goal is to fix some links on `/docs/TESTS.md` file, as described before in this issue (https://github.com/exercism/xjavascript/issues/313#issuecomment-268087800).

**Comment by morrme** [comment]
@rchavarria @matthewmorgan PR submitted .

**Comment by matthewmorgan** [comment]
Closing as wontfix per #556.
