### ISSUE TITLE
JavaScript Track: ES6 Support

### ISSUE THREAD

**Issue by christopherallanperry** [exercism/javascript#387]
Re: https://twitter.com/exercism_io/status/889983074959851520

Does the Exercism JavaScript track fully support the use of ES6 syntax, or is it only the ES6 track that does that?

**Comment by rchavarria** [comment]
From a technical point of view, it depends on the Node.js version you're using to run the code.

From the track's philosophy point of view, the JavaScript track is intended to practice ES5 features, that can be run in all modern and not-so-modern browsers (mobile, <IE11,...) while ECMAScript track is meant to practice recent features of the ECMAScript standard, that are not compatible with all browsers (eventually they will).

As it is technically possible, if you run Node.js v6.11.1 (current stable version) you can write your solutions using some ES6 features (destructuring, optional parameters, string templates, `const` and `let`). But, if you want to practice them, I'd recommend you to practice with ECMAScript track exercises.

I'm wondering about the why of your question, so sorry if the next question sounds rude, it's not my intention: do you miss some exercise in the ECMAScript track? If so, we can help adding it to the track, or we can help you in that task.

**Comment by christopherallanperry** [comment]
Not rude at all. I just found myself using some ES6 syntax as I was going though the earlier JS exercises without thinking about it. I was just curious as to how far that would work, given I knew there was a separate ECMAScript track.

I'm using Node.js v6.11.0 on Windows 10, and v7.2.0 on OSX

**Comment by joelwallis** [comment]
@rchavarria that one is a good question. It's still strange for me that _we have two tracks for the same language_ - if I can put this way. ES6 is JavaScript, and vice-versa. I can understand the desire for a ES track while it was not really fully supported by browsers, but today [it's not really a problem anymore](https://babeljs.io).

Why do we keep two distinguished tracks for something that's really the same thing?

**Comment by rchavarria** [comment]
I'm asking that question every now and then, but I'm never convinced to join the two tracks together.

One feature that makes ES6 more different to ES5 are *modules* (`import` and `export` keywords). And it's not clear at all the ES6 modules will be supported by Node.js ([Stack Overflow to the rescue](https://stackoverflow.com/questions/37132031/nodejs-plans-to-support-import-export-es6-es2015-modules)).

I could argue that ES2016 and beyond will come with key features, and we could benefit from using the transpiler to use them before they're supported by Node.js. But I'm not sure there will be a *key* feature so interesting at the beginning of working with the language that justifies that. 

Anyway, something I'd like to keep is that the `javascript` track doesn't use any transpiler. It would be just the language (and a testing tool). I don't like it to *polute* that track. Unfortunately, nowadays, ES6 modules is the feature that prevents us from merging the tracks :(

**Comment by joelwallis** [comment]
Good point, @rchavarria.

I understand that adding the transpiler to the experience of someone that's trying to _jump on JavaScript_ and just want to learn the basics of the language might not seem to be the ideal and it's something we should work on. However, I don't see the point of keeping two tracks for the same language because Node.js does not support ES6 modules. They are part of the specification and will be supported at some point. It doesn't seem like a good reason to avoid merging them.

We also have the advantage of having the practicality of npm. A single `npm i` can install everything a practitioner would need, including the transpiler. Maybe we should consider it when deciding about it. The JavaScript experience on Exercism could leverage from this merge, since one single track would be easier to maintain than two ones, with distinguished issue trackers, test suites, setups, etc.

**Comment by joelwallis** [comment]
Closing this one, since the question has been answered and additional discussions should happen on dedicated issues.
