### ISSUE TITLE
Use one, track level, package.json

### ISSUE THREAD

**Issue by bdjnk** [exercism/javascript#421]
I realize this was proposed previously (#235) and closed as `wontfix`, but there is a simple and correct way to have a single install of all the necessary tools. The only necessary `package.json` change would be to the `scripts` section.

Right now we have a `package.json` in each exercise with a `scripts` section as follows:

```json
"scripts": {
  "test": "jest --no-cache ./*",
  "watch": "jest --no-cache --watch ./*",
  "lint": "eslint .",
  "lint-test": "eslint . && jest --no-cache ./* "
},
```

All `package.json` files should be removed from the exercise directories, and a single `package.json` would be added to the track directory. The `scripts` section of it should be changed to the following:

```json
"scripts": {
  "test": "jest --no-cache",
  "watch": "jest --no-cache --watch",
  "lint": "eslint --ignore-pattern '*.spec.js'"
},
```

The usage is changed very slightly.

Running `npm test` or `npm run lint` would test and lint, respectively, all exercises. To test or lint a single particular exercise, simply append `-- <exercise-name>`.

So, for example, if I wanted to test the `simple-cipher` exercise I would run `npm test -- simple-cipher`.

I tested this on MacOS and Linux, and it works correctly. I haven't tested it on Windows, but my understanding is that it should work the same way.

I didn't begin with a pull request, although I'd be happy to do so, because I wanted to get feedback and hopefully buy-in before proceeding.

Thanks for reading. Looking forward to your thoughts.

**Comment by matthewmorgan** [comment]
@bdjnk thanks for reviving this, it would be a welcome change.

If I (dimly) recall, the issue was the behavior of Jest either locally or on Travis.  I seem to remember that it wanted to run _all_ tests in the repository when the user's intent was to run tests for a single exercise.

Any change needs to allow for three scenarios:
1. User tests _one_ exercise only
2. Contributor tests everything locally
3. Travis build runs all tests

If your PR would address this, it's warmly welcomed!

**Comment by tejasbubane** [comment]
More importantly we want the users to receive the `package.json` and `package-lock.json` when they run `exercism fetch`. For this we need to keep these files in each exercise.

**Comment by matthewmorgan** [comment]
Ah yes, @tejasbubane there's the rub.  This works for contributors but not for the end user...I had forgotten about that, I knew there was something blocking this.  

@bdjnk I don't think this can be changed without making higher level changes in the exercism CLI application.  I'm not sure what the best way to proceed would be-- could we still create a track-level `package.json` and `package-lock.json` rather than per-exercise?  We would also need to have `exercism fetch` update those track-level files if they change, and perhaps prompt the user to `npm install`.

Maybe a little code duplication is still the best solution.

**Comment by bdjnk** [comment]
I've been mulling this problem. A general technical solution for loading and updating track level files seems like a worthwhile discussion, but also outside the scope of this particular issue.

I can see a simple to implement solution that adds a very slight burden to the end-user up front.

If we put the track level `package.json` in the `hello-world` exercise, all that needs to be added is a single line instruction in the `README` saying to move it up a level into the `ecmascript` directory before running `npm install` there.

This doesn't seem to me an excessive additional burden.

For keeping it updating given changes, that's a more thorny problem that might indeed require the above-mentioned theoretical general purpose solution, but this doesn't feel like an immediate concern.

@tejasbubane @matthewmorgan

**Comment by matthewmorgan** [comment]
@bdjnk I have to say, I'm not convinced that your proposed solution is better than what we have now- -I wish I were convinced, but...  

The current situation is clearly easier for the end user than having to move and/or maintain the package.json file.  It's a small amount of additional work for contributors, but not much, and with the backstop that the files are copied propagated automatically on `make test`, and doublechecked during the Travis build.  Given that users far outnumber contributors, my vote goes toward the users if I have to choose.

I agree it's not an 'excessive burden' on the users, but why do it at all?  Why change the track in a way the requires more of the user to use the core functionality of the application?  I feel that in this case, unless we can shift this work to the CLI, we should not do it at all.

**Comment by bdjnk** [comment]
@matthewmorgan There are two reasons doing this helps the end-users.

As an end-user myself, I was put off by having to reinstall identical `node_modules` in each exercise. So much so I took the time to solve the problem for myself and propose it here. Others may have the same irritation, and indeed, friends I've directed to this track have mentioned it.

More importantly, part of what we're trying to teach is the right way to structure code, and for ECMAScript that very much includes, or should include, the tools, as they're fundamental to the experience in the real world.

**Comment by matthewmorgan** [comment]
@bdjnk thanks for your thoughtful response. 

While I agree that in a real project you would want to do something like this, I'm still put off by the idea of users having to download a specific exercise, and move the files manually before doing the node install.  This is less an architecture question than a limitation of the way the Exercism CLI currently works.  The users are not cloning the entire project repo, but just the contents of each exercise folder one exercise at a time.  

Further, it looks like at the moment, if we were to take this approach, there would be no way to signal to the user that their `package.json` file was out of date, since it would only exist on an exercise they had completed in the past sometime.  This seems overly brittle to me.

Under the current system, the procedure for setting up every exercise involves some repetition, but it's the same each time and per-exercise dependencies are delivered _with the exercise_.

Exercism has to serve users with a wide range of experience levels, and at the lower end of experience,  it's important to keep things as beginner-friendly as possible.  At the higher end, there's nothing to stop a savvier user from doing exactly what you propose with their own local copy of the application.

I don't mean to sound stubborn or ungrateful for your willingness to contribute, but I remain unconvinced.  I think this is an issue where we're dealing with the limitations of some pieces of the infrastructure and every approach has some less-than-ideal features.  If the track maintainers feel your proposed solution, with its issues, is better than what we have with its issues, then I will go with the group consensus.

Having said all that, perhaps there is a way to configure the CLI to address the issues here, but again, that would need to be taken up in that repo.

**Comment by tejasbubane** [comment]
Those were some thoughtful responses @bdjnk. I understand that reinstalling `node_modules` is a bit of a repetitive task and eats up disk space. I myself delete the `node_modules` after completing the exercise but..

I see one problem with your approach - imagine the user does move the package.json up a level for the first exercise - starts solving exercises and sometime later - we the track maintainers decide to add certain extra dependency or change something. User will try to download exercise and assuming the packages are already installed in parent directory, will just run the tests and they will break in unexpected ways.

I agree with @matthewmorgan - unless it is automated and CLI takes care of it considering all the cases (like the one I mentioned above) - I don't recommend putting it on the user to take care of.

**Comment by kytrinyx** [comment]
The new CLI has a command (`exercism prepare --track=$track-id`) that is intended to do this, but I will not be able to implement the guts of it until after launch.

**Comment by matthewmorgan** [comment]
@kytrinyx I'm guessing that's intended to handle track-level installs-- will it receive updates whenever a new exercise is fetched?  If so, it seems like we could pin this for now, and use that feature when it's ready.

**Comment by kytrinyx** [comment]
Yes, let's pin this and come back to it. Thank you!

**Comment by Talicode** [comment]
I am just beginning with Exercism, Typescript and Visual Studio Code, but I have a small note for any other newbies trying to implement bdjnk's solution to stop the duplication of the node_modules
His change to package.json (move it to the track level, and edit as noted above) does work, but to get testing to work with yarn I needed to also move up tsconfig.json or jest wouldn't see it and would instead spit out this error pattern:

    Path\To\Exercism\typescript>yarn test two-fer
    yarn run v1.12.3
    $ jest --no-cache two-fer
    FAIL  two-fer/two-fer.test.ts
    Test suite failed to run
    {
        "messageText": "Cannot read file 'ROOT:\\tsconfig.json': ENOENT: no such file or directory, open 'ROOT:\\tsconfig.json'.",
        "category": 1,
        "code": 5012
    }

      at readCompilerOptions (node_modules/ts-jest/src/utils.ts:94:11)
      at Object.getTSConfig (node_modules/ts-jest/src/utils.ts:206:14)
      at Object.getCacheKey (node_modules/ts-jest/src/preprocessor.ts:83:20)

**Comment by nitwhiz** [comment]
[Lerna](https://github.com/lerna/lerna) anyone?

**Comment by SleeplessByte** [comment]
Yes, both work with our repo, as does hoisting node_modules and symlinking.

**Comment by SleeplessByte** [comment]
Closing this. `npm tink` will fix this, `yarn PnP` has fixed this. We can upgrade to tink when it's ready, or switch to yarn.

**Comment by chrissygonzalez** [comment]
Hi! Apologies for commenting on a closed issue, but in researching what to do with all these `node_modules` folders, I found [npm workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces). Might be an option, and doesn't rely on a separate tool?

**Comment by SleeplessByte** [comment]
Hi @chrissygonzalez , yes! That works, but still requires the outside-of-the-exercise "setup" :)
