### ISSUE TITLE
Providing stub files or solution setup guide for JavaScript track

### ISSUE THREAD

**Issue by a-dpq** [exercism/javascript#424]
I’m fairly new to Exercism and am making my way through the JavaScript track. I’ve found it to be extremely useful so far, but one of the biggest pain points for me is setting up solutions for the tests. Whenever a slightly more complicated test structure comes up, I usually hit a roadblock and have to copy someone else’s setup before I can even get started solving the problem itself.

Except for the first two problems, it looks like no stub files are provided for this track. Yet the tests require a variety of setups, which may not be obvious to beginners or people unfamiliar with testing frameworks. After posting an [issue](https://github.com/exercism/discussions/issues/201) about this in [exercism/discussions](https://github.com/exercism/discussions), I discovered that [some other tracks do provide stub files](https://github.com/exercism/discussions/issues/114), but I haven’t been able to find a discussion about this for the JavaScript track.

Is there a rationale for not providing stub files? One reason I can imagine is that there are multiple ways a given solution could be set up (eg. with classes or prototypes). Perhaps an alternative would be to provide a guide at the beginning of the track that covers the various test structures that users will encounter and provides example setups for these. Another possibility would be to provide partial stub files that define exports and offer hints about the setup.

**Comment by m-a-ge** [comment]
@exercism/javascript I strongly suggest adding solution placeholders for each exercise

**Comment by matthewmorgan** [comment]
@a-dpq thanks for your feedback, especially since it's delivered in a very thoughtful way.  Thanks also to @m-a-ge for your input.

We don't mostly provide stub files, it's true, and your speculation about why is more or less accurate.  A couple of years ago we did have a [discussion](https://github.com/exercism/javascript/issues/128) around this, in which it was decided that the first dozen exercises would have a consistent interface with the test suites, and after that, all bets were off.  This was intentional, to push the user and make them wrestle with the possibilities.  Having said that, I'm not opposed to changing it, and I would be curious to hear what the rest of the maintainers think.

Most of these solutions can be implemented using ES5-style object prototype extension, ES6 classes, or even pure functions.  We intentionally leave that up to the user.

Now, it may be the case that our original intention has been thwarted by the new exercise ordering structure that was implemented recently, and the first twelve are no longer consistent in their interface style.  Whatever the outcome of this discussion, an investigation of that possibility seems warranted.

@exercism/ecmascripts -- any thoughts on this?

**Comment by m-a-ge** [comment]
I am not this track maintainer, but I think ES6 classes are preferable way of doing this, just saying 😄

**Comment by matthewmorgan** [comment]
@m-a-ge yes, but this track is explicitly focused on ES5 features.  We want to give people the option, but I'm not sure we want to _push_ them in that direction.

At some point we have to decide to pull those features in to this track as well, but that feels like a separate piece of work to me.

**Comment by a-dpq** [comment]
Thanks for your response, @matthewmorgan. For what it's worth, the two exercises that posed the biggest challenge for me so far in setting up the solution for the test suite were `clock` and `circular-buffer`. (I've only made it about halfway through the track.) I always try to figure things out on my own, but I don't think I would have been able to get the structure for these exercises right without either a general guide or (in this case) copying someone else's setup, which feels a little defeating.

**Comment by matthewmorgan** [comment]
@a-dpq that's not a good feeling!  Maybe we need to have a look at those APIs and see if they are particularly strange.  It might make sense to either address API problems exercise-by-exercise, or if the API is intentional, to provide stubs in (some?) tough cases.

**Comment by matthewmorgan** [comment]
Hmm...taking a look at clock, I actually think the API is a good lesson-- a fluent, chainable API.  But, I admit that it might not be clear how to set that up in JavaScript, or at all, if you're new to OOP.

Perhaps a stub like this would help:

```javascript
exports.at = at;

function at(hours, minutes) {
  var clock = {};

  clock.valueOf = function () {
  };

  clock.toString = function () {
  };

  clock.plus = function (minutes) {
  };

  clock.minus = function (minutes) {
  };

  clock.equals = function (other) {
  };

  return Object.create(clock);
}
```

This defines the shape of the public API, and the module structure.

**Comment by a-dpq** [comment]
I guess this illustrates the difficulty of providing a stub with just one approach, since the approach I ended up using (object prototype extension) looks quite different but does the same job. And I agree that problems like this should ideally be a learning opportunity. Still, as a beginner/intermediate learner, I felt especially lost as I was trying to set up these two exercises. Perhaps a better approach would be to provide more general guidance on the setup (either for the track overall or on a per-exercise basis) where this could be helpful. It would be good to hear feedback from other learners, since this is just based on my own experience with the track.

**Comment by tleen** [comment]
Stubs have always seemed useful to me for the first few exercises to help people truly new to the language to gain their footing. Especially if [TIMTOWTDI](https://en.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it) or the track has a strong preference one way or another. The barrier for entry for the first few exercises should be IMO fairly low. 

Of course it would be important to document where stubs end and give a good explanation for that first stubless exercies that it is time to start from scratch in crafting solutions! Suddenly having stubs pulled away could be jarring. A user may think they are missing something.

**Comment by rchavarria** [comment]
It seems obvious that more stubs are needed. And I completely agree with @tleen about stubs should not  disapear suddenly.

I have a couple of ideas, maybe, a mix of both will be the better option:

1. Add stubs for the first ten or twelve exercises
2. Add stubs for those exercises marked as *core*, as they will be the first users will work on the next version of exercism

**Comment by tleen** [comment]
For `nextercism` because it is possible to take multiple paths you should identify the possible first no-stub exercises in the core path and via unlocks. I would make a note in the core solution and link to it from the first no-stub unlock.

**Comment by rchavarria** [comment]
So, for Nextercism, all core exercises could have a stub, and non-core exercises could have a note or hint pointing to the exercise that unlocks them. Makes sense.

**Comment by tleen** [comment]
@rchavarria I wouldn't think all core exercises should have stubs, there should be a point where the users should be encouraged to stand on their own a bit more. Where this is could vary per track. 

Also any note concerning stubs would be redundant. I figure the first core exercise should have a good explanation of where the stubs went, and how to start without them. The first non-core exercise without stubs that the user could encounter should point to the core exercise to avoid duplication.

**Comment by rchavarria** [comment]
Only `hello-world` and `leap` have stubs. All core exercises appear at the beginning of the `config.json` file, so all core exercises are currently the first to be proposed to new exercism users (some of the core exercises are hard to solve for beginners I think).

So, if we add stubs at least to all core exercises we wil add stubs to the first set of exercises. Then, we can decide if we add links or stubs to other exercises.

**Comment by m-a-ge** [comment]
@alexch, yeah, I see your point. Sometimes it's hard to find this balance

**Comment by alexch** [comment]
btw I have forged ahead on my own fork with a few experiments... check out https://github.com/alexch/javascript if you're interested in any of the following:

 * remove `xit` and recommend `--fail-fast=true` 
 * remove redundant setup instructions
 * run `node .` to launch a local trivial web server that lists the exercises in `config.json` order, and renders their READMEs in-browser, so users can clone this repo and run or edit the exercises in any order instead of being required to use the `exercism` command-line tool to fetch the next one

(I'm not suggesting to merge that last one into master, but I find it a helpful option when teaching a roomful of students in person)

**Comment by matthewmorgan** [comment]
@alexch we're going to be deprecating this track, and replacing it in Exercism v2 with the EcmaScript track per #556.

Thanks for your comments and work here, you are more than welcome to jump in on that track if you like.  I expect we would hold off on any change like the ones you are proposing until after the migration.
