### ISSUE TITLE
[Proposal] use `esm` instead of `babel`

### ISSUE THREAD

**Issue by bennypowers** [exercism/javascript#451]
Tests currently use babel in order to enable standard syntax (i.e. `import`) in modules.

I propose using `jest -r esm`

It may be that [jest does not yet support esm](https://github.com/facebook/jest/issues/4842), in which case see https://github.com/exercism/ecmascript/issues/450

**Comment by dotnetCarpenter** [comment]
Or use [rollup](https://github.com/rollup/rollup) if you want to use jest + ES2018 syntax, without transpiling everything.

**Comment by tejasbubane** [comment]
@bennypowers @dotnetCarpenter I have not used either of `esm` or `rollup` personally, but here is what I think, I maybe wrong:

> Or use rollup if you want to use jest + ES2018 syntax, without transpiling everything.

`rollup` uses [buble](https://github.com/Rich-Harris/buble) internally, which is still a transpiler. [ref](https://github.com/rollup/rollup/blob/master/package.json#L73)

> Tests currently use babel in order to enable standard syntax (i.e. import) in modules.

We don't use `babel` just for `import`, it allows users to code in modern JS features irrespective of the node version they run their code on. I suppose `esm` is just a module loader.

**Comment by bennypowers** [comment]
esm Just makes es modules work in node. It's literally that simple. `node -r esm` or put some esm directives in your package.json and importing es modules _just works_ .

**Comment by dotnetCarpenter** [comment]
I regress.

@bennypowers I thought you where talking about EcmaScript Modules as in `node --experimental-modules` and not ESM as in [esm, the node module](https://www.npmjs.com/package/esm).

Rollup is a tool to only transpile ESM to require/AMD etc. If buble is included, then it's an opt in to use it or something fundamentally has changed in rollup since I've used it. [esm, the node module](https://www.npmjs.com/package/esm) is similar in what problem it solves but fundamentally different since it's not specific for node and requires transpiling, where as it seems that [esm, the node module](https://www.npmjs.com/package/esm) does not.

**Comment by tejasbubane** [comment]
> esm Just makes es modules work in node. It's literally that simple. node -r esm or put some esm directives in your package.json and importing es modules just works .

That means `esm` is not a drop-in replacement for `babel` right? Babel transpiles user-written modern javascript for [the node version installed on user's machine](https://github.com/exercism/javascript/blob/master/package.json#L34).

**Comment by tejasbubane** [comment]
I don't want to sound rude while closing this issue but I hope you understand. Our users will be using different versions of nodejs on their machines while solving exercises and we want to make sure nothing breaks - hence we have to use a transpiler like `babel`. Thanks ✌️
