### ISSUE TITLE
Blocked from moving onto the next exercise. (Matrix to Linked List)

### ISSUE THREAD

**Issue by amscotti** [exercism/javascript#461]
Hi, I got done with Matrix a bit ago and I seem unable to move onto Linked List. I'm not sure why it will not unlock for me. I'm guessing this may have to deal with the move from Ecmascript to Javascript, but I don't know.

![exercism 2018-08-26 13-02-27](https://user-images.githubusercontent.com/598958/44630738-83d37d80-a930-11e8-8e77-58259c1f78c0.png)

Let me know if there any more details I can share to help with this issue.

Thanks!

**Comment by tejasbubane** [comment]
I guess you are right in that this may be a migration issue. Because the [config](https://github.com/exercism/javascript/blob/master/config.json#L204-L207) says linked list is `core` exercise and is not unlocked by something else. Let me check with the core members and get back to you. Sorry for the inconvenience.

**Comment by paparomeo** [comment]
I've had the same issue: https://github.com/exercism/exercism/issues/4289.

**Comment by iHiD** [comment]
@amscotti Is this fixed for you now?

**Comment by amscotti** [comment]
@iHiD Yup! Thanks for the help, I can now work on Linked List. :) 🎉

**Comment by iHiD** [comment]
Enjoy! :)
