### ISSUE TITLE
Zipper exercise tests with different arity of function toTree

### ISSUE THREAD

**Issue by MarPenc** [exercism/javascript#471]
The [_Zipper_ exercise](https://github.com/exercism/javascript/tree/master/exercises/zipper) tests requires multiple arities of the function _toTree_:

` 31:    expect(zipper.toTree(t1)).toEqual(t1);`

and

` 43:    expect(zipper.left().right().toTree()).toEqual(t1);`

In my opinion, that is not possible to achieve in Javascript, since there is no function overloading technique that I know of.

**Comment by LyleCharlesScott** [comment]
Are you sure this is a thing? I have a solution for this exercise that passes all of these tests.

**Comment by tejasbubane** [comment]
@MarPenc I think that `t1` is already applied in `beforeEach` so not required again in the tests. Thanks for spotting. 👍 

Although it should not be a blocker. You can pass less number of arguments to functions in JS - it won't throw any error - the argument value will just be `undefined`. This might be how @LyleCharlesScott did it. Since the parameter is not required, I will merge your PR.
