### ISSUE TITLE
ESLint reports 1230 errors and 5 warnings

### ISSUE THREAD

**Issue by MarPenc** [exercism/javascript#472]
The readme suggests the use of `npm run lint-test` to _"help you write quality JavaScript code by checking for common formatting errors, enforcing style rules, and suggesting changes that conform to best practices."_ 

ESLint reports 1230 errors and 5 warnings.

This should be fixed.

[lint-test-result.txt](https://github.com/exercism/javascript/files/2363179/lint-test-result.txt)

**Comment by tejasbubane** [comment]
> Many of these errors can be fixed by th--fix parameter for ESLint, or by adding the Prettier package to the repo. The first option is a relatively quick-win, but temporary. The second will probably be better in the long run, but is likely to require a lot of work initially. What's everyone's though on these?

On the contrary I think the second one (prettier) should be easier to do since everything should be formatted in a single command. But we decided against using prettier long back https://github.com/exercism/javascript/issues/298 

Eslint configuration is not complete (open issue https://github.com/exercism/javascript/issues/44) and is not added in CI. Hence all the errors. I am not sure if I have the time to look at each of those eslint rules and decide which ones to use. I would rather go with `eslint:recommended` or `prettier`.

**Comment by xarxziux** [comment]
Prettier or `eslint --fix` will take care of some of the formatting issues, which are the bulk of the errors, but not everything.  It might be worth doing [another](https://github.com/exercism/javascript/pull/320) `eslint --fix` and pulling the lot in one go.

**Comment by tejasbubane** [comment]
This can now be closed in favor of #480
