### ISSUE TITLE
Lint errors with line endings in windows

### ISSUE THREAD

**Issue by Futuro212** [exercism/javascript#502]
Hi everyone,

So I'm new with this project and when I try to run the lint command to solve some errors regarding #480, it shows errors about Expected linebreaks to be 'LF' but found 'CRLF'. I'm running this on windows. Should I change some configuration in the eslint for this?

**Comment by adamxtokyo** [comment]
This has to do with your IDE. I'm guessing you're using Visual Studio Code on Windows? It uses CRLF line endings per default, but you can set it up to use LF line endings instead, which would be a more permanent solution.  

[See this issue for instructions.](https://github.com/Microsoft/vscode/issues/2957)

Good luck, I hope this solves it for you 😄

**Comment by Futuro212** [comment]
I went with another approach, I changed my `.gitattributes` file to keep with the LF line endings, using the git global config.

**Comment by adamxtokyo** [comment]
@Futuro212 that works too, but it also means your local files will keep their `CRLF` line breaks and a conversion will happen on push. Might not make a big difference depending on your workflow, but I'd say changing your IDE settings is better since it will streamline the whole process (i.e. no needless conversion).

Either way, happy to hear you solved the issue 🙂

**Comment by Futuro212** [comment]
That makes sense but solved the CRLF breaks on checkout, because I kept changing options in vscode to LF but the files still came with CRLF (without the `git global config` I mean).

Thanks for the help :) @adamxtokyo

**Comment by adamxtokyo** [comment]
No worries @Futuro212 ! 😌 

Your reply actually made me realise I made a mistake in my previous comment;
Like you said, line breaks are converted on **checkout**, not on push like I said 🤦‍♂️ 😅 

[Here's a good explanation of the different options](https://help.github.com/articles/dealing-with-line-endings/#example)

**Comment by SleeplessByte** [comment]
A better solution would be to change the `eslint` settings in the JavaScript `package.json`s (or move to a config file)

`linebreak-style` needs to be turned off.

**Comment by adamxtokyo** [comment]
Can you elaborate why that would be a better solution?

**Comment by SleeplessByte** [comment]
Changing git attributes in order to match some arbitrary rule that has
nothing to do with JavaScript or modern text editors as they all handle
foreign line endings correctly is imo not a good solution.

As you can see here https://eslint.org/docs/rules/linebreak-style the rule
is just a contingency just in case something misbehaves and it even points
out that git and text editors do NOT need this.

Turning off the rule that doesn't really help anyone and actually gives
windows users something they don't understand (imo is just a continuation
of demonizing windows users), whichbis cryptic at best ánd not part of the
instructions how to get started with JavaScript, is the right approach.

**Comment by SleeplessByte** [comment]
P.S. I'm not trying to sound combative or anything else :) on the spectrum

**Comment by tejasbubane** [comment]
@Futuro212 Please reopen if the issue still persists for you. Thanks!
