### ISSUE TITLE
Non linear learning curve

### ISSUE THREAD

**Issue by jonakirke94** [exercism/javascript#564]
I've done the first 7 exercises of the track and I've experienced the difficulty varies a lot.

I spent 3 hours on "Simple Cipher" but only 5 minutes on "Gigasecond". I'd like to propose "Simple Cipher" to be moved further down the track and "Gigasecond" to the 3rd exercise in the track.

**Comment by matthewmorgan** [comment]
@jonakirke94 do you think the difference is because of 

1. the language -- required features of the language were difficult to understand or use
2. the core problem -- that is, simple-cipher is a harder problem conceptually
3. the implementation -- somehow the test suite made an otherwise easy problem hard to solve

We appreciate you taking the time to give us your thoughts on this.

**Comment by jonakirke94** [comment]
I think it's a combination of 2 & 3. 

I think the exercise was conceptually harder than the nearby tracks and if I had to compare it to the exercises on the sidetrack in terms of difficulty I would rate it medium, which I think is a little too hard for the third exercise in the track.

The steps are intended to make it easier to comprehend and gradually increment your code, but the tests are not coming in the same order - for example you don't need the random key before Step 3 but it's the first test in the test suite which I think adds to the confusion

**Comment by serixscorpio** [comment]
After having started mentoring the simple cipher exercise in javascript track, I tend to agree the core problem is harder comparing to nearby exercises.  This exercise touches upon multiple concepts (from @SleeplessByte's [mentor notes](https://github.com/exercism/website-copy/pull/605/files)):
* DRYing up an implementation
* Maintainability (magic numbers, variable naming)
* Strings as characters and "charCode"
* Modulo arithmetic

This exercise is also a 'longer' exercise that involves more steps comparing to nearby exercises.  A rough sequence would be:

1. Key generation
1. Key validation
1. Transform (encode/decode) single characters
1. Transform (encode/decode) multiple characters

Anecdote: the simple cipher exercise is queued up (i.e. awaiting mentoring) more often than other exercises nearby, probably due to more to discuss and more iterations.

**Comment by SleeplessByte** [comment]
I usually just mentor 15 of simple cipher at a time.

I do think it's a great exercise but should probably be later down the
track

**Comment by SleeplessByte** [comment]
This should be fixed per #590 and further changes coming up.
