### ISSUE TITLE
Add jsdoc to exercises

### ISSUE THREAD

**Issue by nitwhiz** [exercism/javascript#701]
Is it intentionally that I have to look up the input (and output) of the functions to be created in the tests?

I'd suggest to provide the following to each function:

```js
/**
 * @param {string} whateverInput
 * @param {Date} whatnot
 * @returns {boolean}
 **/
export const fn = (whateverInput, whatnot) => {}
```

I'd happily contribute this change if wished.

**Comment by SleeplessByte** [comment]
It is intentional. A lot of the time for those exercise past the first few ones, giving the type, will give away quite a bit of the solution.

I tend to instantly write the JSDoc as I start writing the solution, so I only need to "decide" on it once.

**note**: JSDoc type inference is not a universel IDE feature.

**Comment by nitwhiz** [comment]
Imho does looking into the test give away way more about the solution though. I get the point of "getting used to tests" and I like that but I don't really see any use in having you to guess the type and look into the test code.

**Comment by SleeplessByte** [comment]
Since most of these exercises are meant to be tackled with a TDD-style approach, that's exactly the point :)

It's also a misconception that most of the exercise have a _strict_ output type.  For example, you can type `resistor-color` to have as input a `string`, or a `OneOf` type literal: `'brown' | 'white' | ...`. How would you pick here? Automatic type inference and manual JSDoc writing (by the student) is vastly more flexible in that aspect.

**Comment by nitwhiz** [comment]
Alright, makes sense (:

Oh, that's pretty cool, didn't see that / think of that. Thanks for clarification! :+1:
