### ISSUE TITLE
Recruiting additional maintainers for JavaScript

### ISSUE THREAD

**Issue by kytrinyx** [exercism/javascript#819]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by jocelo** [comment]
I would like to be part of this effort. My name is Alfredo and I have been working with JS for over 6 years. I would like to be a maintainer because I like the value and purpose behind Exercisim. I would like to contribute back to the community as much as I can.

https://exercism.io/profiles/jocelo

**Comment by ovidiu141** [comment]
Hi, my name is Ovidiu. I'm interested in becoming a maintainer for the JS track, because I am a big fan of the exercism platform and also because I want to contribute to real projects using the Javascript language. I am already a contributor on the JS track (mostly syncing unit tests with canonical-data).

https://exercism.io/profiles/ovidiu141

**Comment by paparomeo** [comment]
My name is Pedro. I have been an JavaScript and Python tracks Exercism mentor for a while now, and have made the odd contribution to these tracks, but I would love to contribute more. I'm registering my interest in becoming a JavaScript track maintainer.

https://exercism.io/profiles/paparomeo

**Comment by hayashi-ay** [comment]
Hi, My name is Ayato. I'm a JavaScript tracks student since Jun 2019.
I want to give back to Exercism community because I have learned a lot of things through Exercism.
Also, I'm excited to join this big project.

I already [contributed to Exercism community](https://github.com/exercism/javascript/issues/721), though it's little.

https://exercism.io/profiles/hayashi-ay

**Comment by tejasbubane** [comment]
Hi, my name is Tejas & I am existing maintainer of Javascript track. I would like to focus more on improving `reasonml` track (that lacks attention as of now) - so will be spending comparatively less time on this track. 

@SleeplessByte is another maintainer here. I would still like to remain around and help new mentors with the v3 upgrade - although I cannot commit to number of hours per week at this moment.

Feel free to tag me in issues/PRs and ask for help.

**Comment by msomji** [comment]
Hi my name is Maisam Somji ([msomji](https://exercism.io/profiles/msomji)) and I have been working on multiple different tracks in terms of practicing different exercises/learning new languages, mentoring others in completing their exercises as well as implementing new exercises for the tracks. With about 5 years of experience working with Java/Javascript/Typescript/Ruby I have been a huge proponent of using exercism.io as a tool to help others learn different languages and hone in on their skills.
I would love to become a maintainer in these tracks in order to continue to help grow this platform so that it can impact others in the same way that is has impacted me!

**Comment by aimorris** [comment]
Hi, my name is Adam Morris. I am currently a JavaScript mentor, with years of experience programming using JavaScript. I would love to be considered to become a maintainer for the JS track so I am able to further Exercism and the education/knowledge it brings to new programmers.

https://exercism.io/profiles/Adam-Morris

**Comment by Calamari** [comment]
Hi, Georg here. Since I am mentoring JavaScript and working in that field for a decade or so, I might as well step up and help out a bit, if I can.

**Comment by darthbob88** [comment]
Hello, my name is Raymond Price. I've been mentoring on Exercism for a couple years, and been working in frontend web development for most of the past decade. If nothing else, this will probably be some nice resume polish.

**Comment by TomPradat** [comment]
Hi there, I love exercism and i have some experience with javascript, how could i help ?

**Comment by SleeplessByte** [comment]
I've seen you around @TomPradat . If you're on the mentor slack, ping me and I'll get you onboarded?

**Comment by evelynstender** [comment]
Hi there! I'd love to be part of the maintainers for JS team!

**Comment by SleeplessByte** [comment]
@evelynstender ping me on Slack!

**Comment by junedev** [comment]
There is now a nice, canonical path to become a maintainer for a track, please see https://exercism.org/docs/community/maintainers.
