### ISSUE TITLE
'npm test' command hangs/doesn't exit 

### ISSUE THREAD

**Issue by bobbychicano** [exercism/javascript#890]
Hello, I'm having an issue executing tests in my terminal. When I type in `npm test`, the test will start to run, and then it never exits -- it just hangs there. I have to keep canceling the test with `^C`. After doing some googling this morning I uninstalled and reinstalled npm for node, updated yarn, jest, and homebrew. 

However, none of these actions have solved my issue. I just want to be able to run my tests smoothly again and focus on learning instead of troubleshooting. Can anybody help me out?

Here is the full output on my terminal after running a test: 

```
> exercism-javascript@2.1.0 test /Users/bobbychicano/Exercism/javascript/resistor-color-duo
> jest ./*

 FAIL  ./resistor-color-duo.spec.js
  Resistor Colors
    ✕ Brown and black (2 ms)
    ○ skipped Blue and grey
    ○ skipped Yellow and violet
    ○ skipped Orange and orange
    ○ skipped Ignore additional colors

  ● Resistor Colors › Brown and black

    Remove this statement and implement this function

      5 | 
      6 | export const decodedValue = () => {
    > 7 |   throw new Error("Remove this statement and implement this function");
        |         ^
      8 | };
      9 | 

      at decodedValue (resistor-color-duo.js:7:9)
      at Object.<anonymous> (resistor-color-duo.spec.js:5:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 skipped, 5 total
Snapshots:   0 total
Time:        1.08 s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/node_modules|.\/package-lock.json|.\/package.json|.\/resistor-color-duo.js|.\/resistor-color-duo.spec.js|.\/yarn.lock/i.
```

Thank you.

**Comment by SleeplessByte** [comment]
Hi there!

It's not fun that you're having issues. Sorry for that. I don't know if I'll be able to resolve this for you, but let's try!

### Tools

> After doing some googling this morning I uninstalled and reinstalled npm for node, updated yarn, jest, and homebrew.

In general, you'll never need to uninstall `npm`; instead you would install a new `node` version, and update the `npm` binary that comes with it. In that sense, can you run `node -v` and `npm -v` and give us the output? The current [LTS](https://nodejs.org/en/) is 14.5.0, so we'd expect:

```shell
node -v
v14.15.0

npm -v
6.14.8
```

### System packages

Next, you mention `yarn`, `jest` and `homebrew`. 
- Updating `homebrew` is definitely a good idea. 
- `yarn` isn't used by the `exercism/javascript` track (and is a replacement for `npm` -- we use it in `exercism/typescript`).
- `jest` is used, but should be *installed via package.json*, and not *globally managed*. This means that you'll never need to update your own jest, in order to make `exercism` work.

### Dependencies

That said, the instructions say to go into your exercise directory, and install the dependencies:

```shell
cd /Users/bobbychicano/Exercism/javascript/resistor-color-duo
npm install
```

After its done, the result should be something like (numbers might differ slightly when on different OSes):

```shell
added 915 packages from 421 contributors in 18.136s

48 packages are looking for funding
  run `npm fund` for details
```

### Running the tests

Per the track instructions, tests can be ran with `npm test`. This yields something like:

![Screenshot showing the shell command "npm test" in the resistor-color-duo exercise folder, with one failed jest test](https://user-images.githubusercontent.com/1964376/98043203-21863980-1e25-11eb-983c-d9a50dfb1789.png)

**Note**: there are slight differences in my screenshot versus your output. It _really_ should say `jest --no-cache ./*` (and not `jest ./*`). The process does cleanly exist. If you *must* use CTRL+C, it means that there is something interfering (as you correctly says *hanging*). It is possible that this is us, but it's also possible that it is *completely* unrelated. For example:

- virus scanner is preventing the process to log somewhere
- process tries to log somewhere, but doesn't have access (write access)
- something on your system has modified node to run some code on exit (which hangs)

If you've taken all the above steps, and still get different values, I'm happy to collect a Mac and try to replicate your *exact* system. Feel free to ask anything in this issue.

**Comment by bobbychicano** [comment]
Hi,

Thanks for checking this out for me. I definitely did not know what I was doing and was desperately trying to find a solution. 

This is the output when I run the node and npm commands:

```
node -v
v14.15.0

npm -v
6.14.8
```

Also, thanks for the brief explanation of yarn, jest, and home-brew. That helps put those tools a bit more in perspective. 

I also make sure to run `npm install` for every exercise. This is the output I received when running that command again for the resistor-color-duo exercise:

```
removed 2 packages in 2.913s

48 packages are looking for funding
  run `npm fund` for details
```

Finally, in regard to jest, that was my fault. I had changed the cache setting hoping it did something. I’ve changed it back but it doesn’t solve the issue. 

My only other thoughts are that my javascript could have broken the test? I was trying to solve the reverse-string exercise with recursion and I noticed it caused a bunch of test/statements to come on screen and hang. 

This last part is embarrassing — I didn’t know how to exit the `npm test` command when the test was hanging so I pressed every button on the keyboard and kind of got lucky and accidentally hit control+Z and that suspended the command. Is it possible I changed some setting in terminal just by clicking random keys? 

Thanks for all the help so far! I appreciate your friendliness and your patience with someone that is not as experienced as you.

**Comment by SleeplessByte** [comment]
Would you be so kind to run `npx envinfo --preset jest` and give us the results? This will tell us a bit more about your environment. That way it's easier for me to reproduce, hopefully.

> Finally, in regard to jest, that was my fault. I had changed the cache setting hoping it did something. I’ve changed it back but it doesn’t solve the issue.

It still hangs? You can try to add [`--forceExit`](https://jestjs.io/docs/en/cli.html#--forceexit) to the `package.json` script, or when running in your terminal: `npm test -- --forceExit`. **If** that works, let me know. It's not a solution, but may bring us closer to the issue at hand.

> My only other thoughts are that my javascript could have broken the test? I was trying to solve the reverse-string exercise with recursion and I noticed it caused a bunch of test/statements to come on screen and hang.

If you have an infinite loop, the tests will _definitely_ hang. CTRL+C might not even close it. Without going in too many details (but feel free to ask more), best is to go into the process manager and kill it manually (or use a new terminal and find the process `ps aux`, and kill it `kill -9`). Other option is to restart your computer.

**However**, it shouldn't affect *other* directories --

> Is it possible I changed some setting in terminal just by clicking random keys?

I suppose so! But I wouldn't know what 😅 . Here I would also start with restarting the machine, just in case.

**Comment by bobbychicano** [comment]
Hey SleeplessByte, I hadn't thought about restarting my machine. 

I was hoping it would be that simple, but I just closed all of my applications and restarted and I still have the same issue. 

Here is the result of `npx envinfo --preset jest`:

<img width="641" alt="Screen Shot 2020-11-05 at 10 09 44 AM" src="https://user-images.githubusercontent.com/62775533/98280143-cbfa7b80-1f4f-11eb-937b-84b1e21c0fd2.png">

Also, I tried `npm test -- --forceExit` and it was successful in ending the test. Here is the result: 

<img width="644" alt="Screen Shot 2020-11-05 at 10 12 36 AM" src="https://user-images.githubusercontent.com/62775533/98280218-ed5b6780-1f4f-11eb-8ea1-e9705c17466b.png">

I also tried `npm test -- --detectOpenHandles` like the terminal suggested but that also just hangs and I never got a result. 

Thanks for the quick responses by the way.

**Comment by SleeplessByte** [comment]
> Also, I tried npm test -- --forceExit and it was successful in ending the test. Here is the result:

Okay great. Then at **least** you have a way to do this before we figure out what the heck is going on!

I'm outta ideas at this moment, but will try to reproduce on a Mac here. @NobbZ you have any ideas? Seen this issue on gitter?

**Comment by neenjaw** [comment]
@bobbychicano can you create a gist (gist.github.com) and paste in your exercise file, test file (one ending with spec.js), package.json so we can see if there is something with your code?

**Comment by bobbychicano** [comment]
Hi Neenjaw,

Gist created here: 

https://gist.github.com/bobbychicano/704b3ce296205e5bdf3d60becfcd9204

Thank you.

**Comment by neenjaw** [comment]
It certainly doesn't seem to be anything in your code. Hopefully we can rustle up someone with a mac to be able to help you trouble shoot this.  

Oh, does this always happen with every exercise? or just this one?

**Comment by bobbychicano** [comment]
So far it happens on the reverse-string exercise and on the resistor-color-duo exercise. It definitely wasn't happening before on any of the other exercises I had worked on. 

Thanks for the help so far. I know it can be difficult trying to troubleshoot across the web. Wish there was more I could do to help.

**Comment by SleeplessByte** [comment]
All good. It's interesting. 

Van you post a list or screenshot of your Exercism folder do we know which exercises you did (in an attempt to find commonality between those two and not the rest).

**Comment by NobbZ** [comment]
> @NobbZ you have any ideas? Seen this issue on gitter?

Sorry beeing late, just realised this in my inbox by accident…

No, so far this behaviour has not been mentioned in the gitter, and I even asked an ex coworker (the only one I know im my proximity who has done JS for quite a while now) if he had observed something like this before, though he hasn't as well.

**Comment by bobbychicano** [comment]
Quick update guys: 

I've moved on from the exercises I was having trouble with. I added `--forceExit` in the package.json file so that I could get through them.

I'm currently on the 'triangle' exercise and running `npm test` works smoothly and does not hang. 

Thanks y'all for having taken the time to look into this.

**Comment by SleeplessByte** [comment]
I'll close it as "non-reproducible", but if you or anyone else has this issue, feel free to post again or open a new issue.
