### ISSUE TITLE
two-bucket: fix implemenation

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#901]
Don't work on this issue until #895 is merged, or use that PR as a base branch.

When `two-bucket` was synced, it became evident that some of the tests cases are not passing, at all. Fix the implementation so these test cases pass and replace `test.skip` with `xtest`: https://github.com/exercism/javascript/blob/774fb12c4d1f492af9658ece4eec515bf92552e7/exercises/two-bucket/two-bucket.spec.js

**Comment by slaymance** [comment]
Hey @SleeplessByte I noticed the tests throwing for this exercise and submitted a fix in [PR 905](https://github.com/exercism/javascript/pull/905). We'll still need another PR to update the example solution since it's failing a couple of the new tests, and running into an infinite loop on a couple of them. With this PR, though, we can at least get the tests working for students.
