### ISSUE TITLE
High Scores: tests should check for mutated arrays

### ISSUE THREAD

**Issue by slaymance** [exercism/javascript#931]
I've talked with a couple fellow learners about this exercise and notice the tests don't check for mutated arrays. This allows for our code to pass all the tests while being flawed due to mutated arrays. Here's an example of a solution with a bug:
```javascript
export class HighScores {
  constructor(input) {
    this.scoresArray = input;
  }

  get scores() {
    return this.scoresArray;
  }

  get latest() {
    return this.scores[this.scores.length-1];
  }

  get personalBest() {
    return Math.max(...this.scores);
  }

  get personalTopThree() {
    return this.scores.sort((a,b) => b-a).slice(0, 3);
  }
}
```
If we look at the `latest` getter, we see it just grabs the last score in the `scoresArray`. However, in the `personalTopThree` getter, it uses `.sort()` to get the top three scores, mutating the `scoresArray`. This will cause the `latest` getter to return a different score once called again.

It's a valuable opportunity to teach about mutability (I've also seen some solutions utilizing `.pop()` and `.shift()`). It should be an easy lift: adding some tests which check to see if the value for `latest` is the same before and after calling for `personalTopThree` and doing the same for the `scores` getter.

**Comment by SleeplessByte** [comment]
This is a great addition for the _canonical data_ because other tracks will have *the same issue*.

PR [this file](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json). You can use the scenario `local-scope` for this test. Make sure to link to this issue in the PR. You probably want to use a _new_ non-exising property, for example `topThreeFollowedByLatest` or whatever seems sane. 

In the JavaScript PR we would _not_ use a new property but simulate it: call `personalTopThree` and then `latest` and see if it's still correct.
